= galaxixs(6) =
:doctype: manpage

== NAME ==
greed - eat a game field until you run out of moves

== SYNOPSIS ==
galaxis [-s]

[[description]]
== DESCRIPTION ==

The object of Greed is to erase as much of the screen as
possible by moving around in a grid of numbers.  To move your cursor,
simply use your arrow keys or the the 'hjklyubn' keys or your numeric
keypad (with Num Lock on).  Your location is signified by the @
symbol. The following diagram shows how the basic movement keys
work.

----
y k u  7 8 9
 \|/    \|/
h-+-l  4-+-6
 /|\    /|\
b j n  1 2 3
----

When you move in a direction, you erase N number of grid squares in
that direction, N being the first number in that direction.  Your
score reflects the total number of squares eaten.

Greed will not let you make a move that would have placed you off the
grid or over a previously eaten square. If no valid moves exist, your
game ends.

Other Greed commands are 'Ctrl-L' to redraw the screen, 'p' to toggle
the highlighting of the possible moves, and 'q' to quit.  

The only command line option to Greed is '-s' to output the high
score file.

[[environment]]
== ENVIRONMENT ==
The environment variable GREEDOPTS can override the default
color set, which will be parsed as a string of the form:

----
	<c1><c2><c3><c4><c5><c6><c7><c8><c9>[:[p]]
----

where <cn> is a character decribing the color for digit n.
The color letters are read as follows:

----
	b = blue,
	g = green,
	c = cyan,
	r = red,
	m = magenta,
	y = yellow,
	w = white.
----

In addition, capitalizing a letter turns on the A_BOLD attribute for that
letter.

If the string ends with a trailing :, letters following are taken as game
options. At present, only 'p' (equivalent to an initial 'p' command) is
defined.


[[files]]
== FILES ==
/usr/lib/games/greed.hs::
   Default location of Greed high scores.
~/.greedscores::
   Where they're put if the default location cannot be written to..

[[authors]]
== AUTHORS == Originally written
Written by Matt Day.  Maintained by <esr@snark.thyrsus.com>. See ESR's home
page at http://www.catb.org/~esr/ for
updates and other resources.

[[bugs]]
== BUGS ==
This really ought to be an X game, but that would have been too much
like work.

// end
